import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import SessionWrapper from "@/components/SessionWrapper";
import Leftsidebar from "@/components/left-sidebar";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/authOptions";
import RightSidebar from "@/components/RightSidebar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionWrapper session={session}>
       
            <div className="flex">
              <div className="sm:w-[280px] h-screen fixed top-0 left-0">
                <Leftsidebar />
              </div>

              <main className="sm:ml-[280px] mb-[4em] sm:p-4">
                {children}
              </main>

              <div className="pr-10">
                <RightSidebar />
              </div>
            </div>
          
        </SessionWrapper>
      </body>
    </html>
  );
}
